### ISSUE TITLE
Cannot display username correctly

### ISSUE THREAD

**Issue by vhgn** [unixporn/Mi#1]
As you can see in [this](https://discordapp.com/channels/635612648934735892/655947537538088962/697007339206737931) message, it does something wrong, where it doesn't get String, but gets undefined, and parsing it to string is `undefined` (that's my guess).
<img width="304" alt="Screen Shot 2020-04-07 at 13 26 58" src="https://user-images.githubusercontent.com/36004230/78652958-7be10b00-78d3-11ea-93d0-f89ccd5ee475.png">

**Comment by vhgn** [comment]
It is from this line.
https://github.com/unixporn/Mi/blob/bac08a9763bb6fb90fd230e094ee78dba29b954e/src/commands/descriptionEdit.js#L74

**Comment by vhgn** [comment]
I am no expert, but I think it should be like this.

```diff
- `Set **description** of user **${message.author}**.` 
+ `Set **description** of user **${message.author.tag}**. `
```

**Comment by aosync** [comment]
I have corrected it in [this pull request](https://github.com/unixporn/Mi/pull/2). Message author is somehow undefined. And even if it was defined it wouldn't be an string anyways. I replaced it by `authorDisplayName` because that's how the rest of the project does in those cases.
